# Part 1: Launching a Duet Server

In [1]:
import syft as sy

In [2]:
duet = sy.launch_duet(loopback=True)

🎤  🎸  ♪♪♪ Starting Duet ♫♫♫  🎻  🎹

♫♫♫ > DISCLAIMER: Duet is an experimental feature currently in beta.
♫♫♫ > Use at your own risk.


    > ❤️ Love Duet? Please consider supporting our community!
    > https://github.com/sponsors/OpenMined

♫♫♫ > Punching through firewall to OpenGrid Network Node at:
♫♫♫ > http://ec2-18-218-7-180.us-east-2.compute.amazonaws.com:5000
♫♫♫ >
♫♫♫ > ...waiting for response from OpenGrid Network... 
♫♫♫ > DONE!

♫♫♫ > STEP 1: Send the following code to your Duet Partner!

import syft as sy
duet = sy.join_duet(loopback=True)

♫♫♫ > Connecting...

♫♫♫ > CONNECTED!



# Part 2: Uploading data to the Duet Server

In [3]:
from sklearn import datasets
import torch as th

In [4]:
iris = datasets.load_iris()
X, y = iris.data, iris.target

In [5]:
print("data",X[0:5])

data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
print("target",y)

target [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
print("Length of dataset",len(X))

Length of dataset 150


In [9]:
print(type(X))

<class 'numpy.ndarray'>


In [10]:
X = th.FloatTensor(X)
y = th.FloatTensor(y)

In [11]:
print(type(X))

<class 'torch.Tensor'>


In [12]:
X = X.tag("iris-data")
y = y.tag("iris-target")

X = X.describe("This is a dataset for the classification of flowers of 150 samples with 4 features: sepal length, sepal width, petal length, petal width all in cm")
y=y.describe("Labels for flowers: Iris-setosa, Iris-versicolour, Iris-virginica")


In [13]:
data_pointer = X.send(duet, pointable=True)
target_pointer = y.send(duet, pointable=True)

In [14]:
duet.store

[<syft.proxy.torch.TensorPointer object at 0x0000020368E20130>, <syft.proxy.torch.TensorPointer object at 0x0000020368E20340>]

In [15]:
duet.store.pandas

ID           Tags  \
0  <UID: 7f8bebefea6449b190099da8e2435d67>    [iris-data]   
1  <UID: 38f7a0c80e894ce3a6ff2260b62db22f>  [iris-target]   

                                         Description             object_type  
0  This is a dataset for the classification of fl...  <class 'torch.Tensor'>  
1  Labels for flowers: Iris-setosa, Iris-versicol...  <class 'torch.Tensor'>

In [16]:
duet.requests.add_handler(action="accept")